export const chatUi = {
  shell: "chat-shell",
  panel: "chat-panel",
  panelStrong: "chat-panel-strong",
  panelQuiet: "chat-panel-quiet",
  header: "chat-header",
  divider: "chat-divider",
  pill: "chat-pill",
  button: "chat-button",
  buttonPrimary: "chat-button-primary",
  buttonSecondary: "chat-button-secondary",
  buttonGhost: "chat-button-ghost",
  inputShell: "chat-input-shell",
  input: "chat-input",
  searchInput: "chat-search-input",
  modalBackdrop: "chat-modal-backdrop",
  modal: "chat-modal",
  empty: "chat-empty",
  replyPreview: "chat-reply-preview",
  messageBubble: "chat-message-bubble",
  messageBubbleSender: "chat-message-bubble-sender",
  messageBubbleReceiver: "chat-message-bubble-receiver",
  subtleLabel: "chat-subtle-label",
  muted: "chat-muted",
} as const;
